### Sent POST for login user
POST http://localhost:3000/api/users/login
Content-Type: application/json

{
  "email": "reinaldo@gmail.com",
  "password": "123"
}

### Sent POST for register new user
POST http://localhost:3000/api/users/created
Content-Type: application/json

{
  "email": "junior@gmail.com",
  "password": "123"
}

### Sent POST for created new user
GET http://localhost:3000/api/users/i
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY1MzVkZGZmNWIxOTIwODk2NzZiODdhZCIsImlhdCI6MTY5ODAyOTA2MX0.h0D_o_DwIrJZbGXUhBCje6tKus-2xdxppyaQUNe6P6U

### Sent GET for data the users with appointments
GET http://localhost:3000/api/users/appointments
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY1MzVkZGZmNWIxOTIwODk2NzZiODdhZCIsImlhdCI6MTY5ODAyOTA2MX0.h0D_o_DwIrJZbGXUhBCje6tKus-2xdxppyaQUNe6P6U

### Sent POST for created new appointment
POST http://localhost:3000/api/appointments/created
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY1MzVkZGZmNWIxOTIwODk2NzZiODdhZCIsImlhdCI6MTY5ODAyOTA2MX0.h0D_o_DwIrJZbGXUhBCje6tKus-2xdxppyaQUNe6P6U

{
  "date": "2023-10-30T15:30:00",
  "service": "corte de cabelo 214"
}




### Get all appoitments
GET http://localhost:3000/api/appointments/all







### Sent POST for created new user
GET http://localhost:3000/api/users/logout
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2OTgwMDc1MzB9.z7pPV3951kbWrq1mGPk4JTy5cbmnToThxjl_qMBS0YI








